name: lot_i2c
description: "`lot_i2c` is a library to communicate with i2c slave devices."
version: 0.2.0
repository: https://github.com/hhk7734/flutter_lot_i2c

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  ffigen: ^2.4.2

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: LotI2cPlugin
